project:
  type: book
  output-dir: docs

book:
  title: "MATH/STAT 455: Mathematical Statistics"
  output-file: "math-stat-455"
  author: "Taylor Okonek"
  date: "12/7/2023"
  search: true
  repo-url: https://github.com/taylorokonek/MathematicalStatistics/
  site-url: https://math-stat-455.com
  downloads: [pdf]
  sidebar:
    style: docked
    background: "#7b9f9e"
    fontcolor: "#000000"
    linkcolor: "#000000"
  chapters:
    - index.qmd
    - probability.qmd
    - mle.qmd
    - mom.qmd
    - properties.qmd
    - consistency.qmd
    - asymptotics.qmd
    - computation.qmd
    - bayes.qmd
    - decision.qmd
    - hypothesis.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
    linkcolor: "#24605e"
    backgroundcolor: "#faf7e7"
    fontcolor: "#000000"
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  freeze: auto

