project:
  type: book

book:
  title: "MATH/STAT 455: Mathematical Statistics"
  author: "Taylor Okonek"
  date: "12/7/2023"
  search: true
  repo-url: https://github.com/taylorokonek/MathematicalStatistics/
  downloads: [pdf]
  sidebar:
    style: docked
    background: light
  cover-image: cover.png
  cover-image-alt: |
    Alternative text describing the book cover
  chapters:
    - index.qmd
    - probability.qmd
    - mle.qmd
    - mom.qmd
    - properties.qmd
    - consistency.qmd
    - asymptotics.qmd
    - computation.qmd
    - bayes.qmd
    - decision.qmd
    - hypothesis.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

