# Maximum Likelihood Estimation

In *Probability*, you calculated probabilities of events by assuming a probability model for data and then *assuming you knew the value of the parameters* in that model. In *Mathematical Statistics*, we will similarly write down a probability model but then we will use observed data to *estimate the value of the parameters* in that model.

There is more than one technique that you can use to estimate the value of an unknown parameter. You\'re already familiar with one technique---**least squares estimation**---from *STAT 155*. We\'ll review the ideas behind that approach later in the course. To start, we\'ll explore two other widely used estimation techniques: **maximum likelihood estimation** (this chapter) and the **method of moments** (next chapter).

## Learning Objectives

By the end of this chapter, you should be able to...

-   Derive maximum likelihood estimators for parameters of common probability density functions

-   Calculate maximum likelihood estimators "by hand" for common probability density functions

-   Explain (in plain English) why maximum likelihood estimation is an intuitive approach to estimating unknown parameters using a combination of (1) observed data, and (2) a distributional assumption

## Reading Guide

Associated Readings: Chapter 5 (Introduction through Example 5.2.5)

### Reading Questions

1.  What is the intuition behind the maximum likelihood estimation (MLE) approach?

2.  What are the typical steps to find a MLE? (see Ex 5.2.1, 5.2.2, and
    Case Study 5.2.1; work through at least one of these examples in detail,
    filling in any steps that the textbook left out)

3.  Are there ever situations when the typical steps to finding a MLE
    don\'t work? If so, what can we do instead to find the MLE? (see Ex
    5.2.3, 5.2.4)

4.  How do the steps to finding a MLE change when we have more than one unknown parameter? (see Ex 5.2.5)

## Definitions

You are expected to know the following definitions:

**Likelihood Function**

Explanation

**Maximum Likelihood Estimate (MLE)**

**Order Statistic**

## Theorems

## Worked Examples

**Problem 1:**
